# Generated by Django 5.1.4 on 2025-01-02 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxify_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=50, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
    ]
