# Generated by Django 5.1.4 on 2025-01-06 17:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxify_user', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_custome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('user_role', models.CharField(choices=[('admin', 'Admin'), ('publisher', 'Publisher'), ('influencer', 'Influencer'), ('advertiser', 'Advertiser')], default='advertiser', max_length=20)),
                ('user_name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=10)),
                ('pin_code', models.CharField(max_length=6)),
                ('adress', models.TextField()),
                ('profile_photo', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AddField(
            model_name='verification',
            name='verifyed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='help',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help', to='fluxify_user.user_custome'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='fluxify_user.user_custome'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verificatio', to='fluxify_user.user_custome'),
        ),
    ]
