# Generated by Django 5.1.4 on 2025-01-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxify_user', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custome',
            name='mail_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user_custome',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user_custome',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user_custome',
            name='user_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
