# Generated by Django 5.1.4 on 2025-01-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxify_user', '0005_alter_user_custome_mail_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_custome',
            old_name='adress',
            new_name='address',
        ),
    ]
