# Generated by Django 5.1.4 on 2025-01-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxify_user', '0006_rename_adress_user_custome_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user_custome',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
