# Generated by Django 5.1.4 on 2025-01-12 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxify_user', '0007_alter_report_report_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custome',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
