# Generated by Django 5.1.4 on 2025-01-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxify_user', '0008_alter_user_custome_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custome',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='images/'),
        ),
    ]
