# Generated by Django 5.1.4 on 2025-01-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxify_user', '0010_alter_user_custome_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custome',
            name='profile_photo',
            field=models.ImageField(blank=True, default='/images/default-avatar.png', null=True, upload_to='images/'),
        ),
    ]
