# Generated by Django 5.1.4 on 2025-01-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxify_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1),
        ),
    ]
