# Generated by Django 5.1.4 on 2025-01-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxify_post', '0003_alter_post_posted_by_alter_review_review_by'),
        ('fluxify_user', '0004_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='post_mark',
        ),
    ]
