# Generated by Django 5.1.4 on 2025-01-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxify_post', '0004_rename_post_post_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_mark',
            name='status',
        ),
    ]
