# Generated by Django 5.1.4 on 2025-01-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxify_post', '0005_remove_post_mark_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_mark',
            name='post_image',
            field=models.ImageField(upload_to='posts/images/'),
        ),
    ]
